
spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
logging:
  level:
    web: debug